RigsOfRods/ror-server

source/server/config.cpp
source/server/config.h
source/server/listener.cpp
source/server/listener.h
source/server/logger.cpp
source/server/messaging.cpp
source/server/messaging.h
source/server/notifier.cpp
source/server/notifier.h
source/server/rorserver.cpp
source/server/sequencer.cpp
source/server/sequencer.h
source/server/utils.cpp
source/server/utils.h

Cleanups and minor tweaks.
Commit https://github.com/RigsOfRods/ror-server/commit/2cd3bc7c38f2d40b25cb25a446cfbbde59ce7289 shows how I'd like to design manager/singleton-style APIs. It's in the spirit of https://github.com/RigsOfRods/rigs-of-rods/issues/839. Please discuss.

Cleanups and refactoring

---

.travis.yml

- removed redundant clang install (already installed)
- print cpu model of build host
- removed static analysis
- make use of faster container-based infrastructure (no sudo)
- remove skip_join for IRC bot, it requires special channel permissions

[Tools] Travis: some tweaks

---

dependencies/angelscript/CMakeLists.txt
dependencies/ctemplate/CMakeLists.txt
dependencies/jsoncpp/CMakeLists.txt
dependencies/rudeconfig/CMakeLists.txt
dependencies/socketw/CMakeLists.txt

... to avoid complains with -Werror

[Change] Disable warnings for dependencies

---

.gitignore
contrib/example-config.cfg
dependencies/ctemplate/src/ctemplate/template_string.h.in
dependencies/ctemplate/src/template.cc
dependencies/ctemplate/src/template_cache.cc
dependencies/ctemplate/src/template_dictionary.cc
dependencies/ctemplate/src/windows/ctemplate/per_expand_data.h
dependencies/ctemplate/src/windows/ctemplate/template_cache.h
dependencies/ctemplate/src/windows/ctemplate/template_namelist.h
dependencies/ctemplate/src/windows/ctemplate/template_string.h
source/gui/CMakeLists.txt
source/server/CMakeLists.txt
source/server/broadcaster.cpp
source/server/config.cpp
source/server/master-server.cpp
source/server/master-server.h
source/server/messaging.cpp
source/server/messaging.h
source/server/mongoose.c
source/server/rorserver.cpp
source/server/sequencer.cpp
source/server/sequencer.h
source/server/webserver.cpp
source/server/webserver.h

Same as #41, but this time with squashed commits

🐛 Fixed building with webserver on linux

---

source/common/UnicodeStrings.h
source/server/config.cpp
source/server/logger.cpp

Removed warnings about empty lines in config

---

source/protocol/rornet.h

-> https://github.com/RigsOfRods/rigs-of-rods/pull/1772

Fixed broken actor stream register

---

source/server/sequencer.cpp

Fixes: https://github.com/RigsOfRods/ror-server/issues/35

🐛 Fixed crash on exit

---

source/server/http.cpp
source/server/master-server.cpp
source/server/master-server.h
source/server/rorserver.cpp
source/server/sequencer.cpp
source/server/sequencer.h

🐛 Attempt to fix the crash on sending heartbeats

---

dependencies/angelscript/include/angelscript.h

https://www.gamedev.net/forums/topic/668682-gcc-51-deprecated-warnings/?tab=comments#comment-5230861

Fix compiling with AngelScript on Linux

---

source/server/sequencer.cpp
source/server/userauth.cpp
source/server/userauth.h

It got nuked by this commit: https://github.com/RigsOfRods/ror-server/commit/16d3488763dd57e24e954fb1bfba23d6ceb7c46e#diff-4d84fa7ccba1464b3b460a01a3f8e7c5

🔧 Revived basic user auth functionality

---

source/server/ScriptEngine.cpp

Fixes: https://github.com/RigsOfRods/ror-server/pull/66

🔧 ScriptEngine fix

---

dependencies/socketw/sw_base.cxx

🔧 Enable 'TCP_NODELAY'

---

source/server/sequencer.cpp

Fixes: https://github.com/RigsOfRods/ror-server/issues/32
https://github.com/RigsOfRods/ror-server/commit/7220d8331f56046dc50b504d0756a068e530be8e#diff-4d84fa7ccba1464b3b460a01a3f8e7c5R1367 :angry:

🐛 Fixed the player stats

---

source/server/logger.cpp

Fixes: https://github.com/RigsOfRods/ror-server/issues/2

🐛 Fixed the logrotate support

---

source/server/messaging.cpp

Goes hand in hand with: https://github.com/RigsOfRods/rigs-of-rods/pull/2221

🔧 Another attempt to reduce the network latency

---

source/protocol/rornet.h

Required for:
* https://github.com/RigsOfRods/rigs-of-rods/pull/2232
* https://github.com/RigsOfRods/rigs-of-rods/pull/2233
* https://github.com/RigsOfRods/rigs-of-rods/pull/2234

🔧 Protocol bump

---

source/protocol/rornet.h
source/server/listener.cpp
source/server/messaging.cpp

Goes hand in hand with: https://github.com/RigsOfRods/rigs-of-rods/pull/2241

🔧 Recv fix

---

source/server/broadcaster.cpp
source/server/broadcaster.h

This should result in more reasonable warnings regarding the network quality.

🔧 Improved net quality measurement

---

source/server/sequencer.cpp

Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2314

Fixed stream registration with spaces in filename

---

source/server/config.cpp
source/server/userauth.cpp

🔧 Fixes to user auth

---

source/protocol/rornet.h

This is preparation for the next release.
Supporting PR: https://github.com/RigsOfRods/rigs-of-rods/pull/2473

Bump RoRNet version to 2.42

---

.gitignore
source/server/sequencer.cpp

@AnotherFoxGuy @only-a-ptr Please merge ASAP

Prevent ban list from showing for unauthorized users

---

source/protocol/rornet.h

and bumped protocol version to 2.43

Increased net flares to 10

---

source/server/sequencer.cpp

For easier administration tasks

Added user ip info

---

source/server/blacklist.cpp
source/server/sequencer.cpp
source/server/sequencer.h

This fixes the !unban command since currently we store a -1 for client ids.
Closed #102

Fix the ability to unban

---

README.md

Updated build status in README.md

---

source/server/sequencer.cpp

Show ip in !list command if given from mod/admin

---

CMakeLists.txt
contrib/postinst.in
dependencies/jsoncpp/CMakeLists.txt
dependencies/socketw/CMakeLists.txt
source/server/CMakeLists.txt

Running the setup script now can be disabled with `PACKAGING=TRUE`
Also added packaging with cpack

🔧 Improve install logic

---

source/protocol/rornet.h
source/server/sequencer.cpp

See https://github.com/RigsOfRods/rigs-of-rods/pull/2949
Update: Also see https://github.com/RigsOfRods/rigs-of-rods/pull/2937

RoRnet version bump - Prop anims + Lightmask

---

contrib/example-script.as

Tested to work locally with 2 clients. Some callbacks alow multiple handlers, some allow only one - I documented it the way it behaves, even if it may be a bug.
If you enable the script in config (`scriptname=`), you should see this in the log:
```
08-01-2023 02:52:16|t46148| INFO|ScriptEngine: success: Added a 'frameStep' callback for: void frameStep(float)
08-01-2023 02:52:16|t46148| INFO|ScriptEngine: success: Added a 'playerDeleted' callback for: void playerDeleted(int, int)
08-01-2023 02:52:16|t46148| INFO|ScriptEngine: success: Added a 'playerAdded' callback for: void playerAdded(int)
08-01-2023 02:52:16|t46148| INFO|ScriptEngine: success: Added a 'streamAdded' callback for: int streamAdded(int, StreamRegister@)
08-01-2023 02:52:16|t46148| INFO|ScriptEngine: Executing main() …
```

Added example script with documentation.
